### PR TITLE
Prepare release to zenodo

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by maxnoe** [comment]
@rlopezcoto @morcuended @Bultako @SeiyaNozaki @FrancaCassol 

Please let me know (or edit the .zenodo.json file directly) if you want your orcids/affiliations included

**Comment by maxnoe** [comment]
@vuillaut I copied your affiliation from pyirf, so  you might want to fix it also there.

The main reason for .zenodo.json was author orcids / affiliations and keywords, if that is better solved with something else, I am all for using something else.

**Comment by maxnoe** [comment]
@vuillaut What should we do here? I.e. is it better to use citation.cff for the author orcid / institutes or is zenodo.json fine?

**Comment by maxnoe** [comment]
@FrancaCassol  @moralejo @rlopezcoto @Bultako @SeiyaNozaki  If you want to be included, could you please post your institute and/or ORCID

**Comment by vuillaut** [comment]
Ok, I think we can move on with this `.zenodo.json` for now.

I checked that incomplete `.zenodo.json` is fine, Zenodo will get the missing metadata from GitHub.

Note that legally, a change of license (which is the case in this PR) should require the approval of all contributors (yes I know, annoying, just saying).

**Review by vuillaut — APPROVED** [review]

**Comment by Bultako** [comment]
I copy here my metadata missing from the .json

```
        {
        "name": "Jose Enrique Ruiz",
        "orcid": "0000-0003-3274-4445",
        "affiliation": "Instituto de Astrofísica de Andalucía - CSIC, Glorieta de la Astronomía s/n, 18008, Granada, Spain"
         },

```

**Pull request merged**
