### PR TITLE
Start working on support for EVBc6 CTA R1 data

### PR DESCRIPTION
**Pull request by maxnoe**
Note: this PR goes to the 0.18.x branch, that is the branch that is still using ctapipe 0.12, required by the current version of lstchain.

Tests are failing in CI, since the data files are not available (the only ones available at the moment are too big).

### CODE REVIEW

**Comment by maxnoe** [comment]
Side note: we discussed some time ago about merging the efforts with `ctapipe_io_nectarcam` to have a `ctapipe_io_zfits`.

I think it's time to think about that and have a new event source that works only on the CTA R1 data and for both LSTCam and NectarCam.

@jlenain

**Comment by jlenain** [comment]
> Side note: we discussed some time ago about merging the efforts with `ctapipe_io_nectarcam` to have a `ctapipe_io_zfits`.
> 
> I think it's time to think about that and have a new event source that works only on the CTA R1 data and for both LSTCam and NectarCam.
> 
> @jlenain

Hi @maxnoe !
Yes, definitely! Let me include here @tibaldo , who is much more knowledgeable than me on R0->R1 conversion for NectarCAM.

**Comment by tibaldo** [comment]
> > Side note: we discussed some time ago about merging the efforts with `ctapipe_io_nectarcam` to have a `ctapipe_io_zfits`.
> > I think it's time to think about that and have a new event source that works only on the CTA R1 data and for both LSTCam and NectarCam.
> > @jlenain
> 
> Hi @maxnoe ! Yes, definitely! Let me include here @tibaldo , who is much more knowledgeable than me on R0->R1 conversion for NectarCAM.

Yes, definitely, please keep me in the loop when you get started.

**Review by moralejo — APPROVED** [review]

**Comment by maxnoe** [comment]
tests are continuing with current ctapipe and lstchain, this is not needed anymore

**Pull request closed without merging**
