### PR TITLE
Fill r1 event type also for old data

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by TjarkMiener** [comment]
Thanks a lot @maxnoe! It worked for me locally, but it seems to fail the CI test for the older ctapipe version.

**Comment by maxnoe** [comment]
Should be fixed no @TjarkMiener

**Comment by maxnoe** [comment]
@TjarkMiener fixed now

**Review by TjarkMiener — APPROVED** [review]
Works like a charm!

**Review by morcuended — APPROVED** [review]

**Review by moralejo — APPROVED** [review]

**Pull request merged**
