### PR TITLE
Added missing units in the time step of the reference pulse shape

### PR DESCRIPTION
**Pull request by moralejo**
The u.ns was missing, this made trouble for the pulse integrators

### CODE REVIEW

**Comment by pawel21** [comment]
Did you try pulse integrators?
Because, I got error: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-ca4d118290a7> in <module>
----> 1 extractor(ev.r0.tel[1].waveform, 1, x)

~/anaconda3/envs/lst-dev-ctapipe0.8/lib/python3.7/site-packages/ctapipe/image/extractor.py in __call__(self, waveforms, telid, selected_gain_channel)
    505             self.sampling_rate[telid],
    506         )
--> 507         charge *= self._calculate_correction(telid=telid)[selected_gain_channel]
    508         return charge, peak_time
    509 

~/anaconda3/envs/lst-dev-ctapipe0.8/lib/python3.7/site-packages/ctapipe/image/extractor.py in _calculate_correction(self, telid)
    493             (1 / readout.sampling_rate).to_value("ns"),
    494             self.window_width.tel[telid],
--> 495             self.window_shift.tel[telid],
    496         )
    497 

~/anaconda3/envs/lst-dev-ctapipe0.8/lib/python3.7/site-packages/ctapipe/image/extractor.py in integration_correction(reference_pulse_shape, reference_pulse_sample_width_ns, sample_width_ns, window_width, window_shift)
    228         )
    229         n_samples = sampled_pulse.size
--> 230         start = sampled_pulse.argmax() - window_shift
    231         start = start if start >= 0 else 0
    232         end = start + window_width

ValueError: attempt to get argmax of an empty sequence

**Comment by moralejo** [comment]
> Rather change the function `read_pulse_shapes` to return the values with units and add a docstring please

Ok, will do.

**Comment by moralejo** [comment]
Yet another error... I am afraid I wrote the axes of the reference pulse shape array (gain, sample) in the wrong order! Will need another release, fix will be there soon. Sorry!

**Comment by rlopezcoto** [comment]
> Will need another release,  fix will be there soon. Sorry!
no worries, another release will anyways be needed, but let's try to put everything we know about together before the next one (and before merging https://github.com/cta-observatory/cta-lstchain/pull/457).

**Comment by moralejo** [comment]
> Rather change the function `read_pulse_shapes` to return the values with units and add a docstring please

done

**Comment by vuillaut** [comment]
Again, job is passing:
https://travis-ci.com/github/cta-observatory/ctapipe_io_lst/jobs/358396140
I don't understand why Travis is not reporting correctly.

**Comment by FrancaCassol** [comment]
> Again, job is passing:
> https://travis-ci.com/github/cta-observatory/ctapipe_io_lst/jobs/358396140
> I don't understand why Travis is not reporting correctly.

The problem is that one can not merge ...

**Pull request merged**
