### PR TITLE
Update following changes made in lstchain on pointings

### PR DESCRIPTION
**Pull request by labsaha**
Following recent changes in the `lstchain` repo for drive pointings, we need to update `LSTDriveContainer` class as well.

### CODE REVIEW

**Comment by labsaha** [comment]
@rlopezcoto It is just cosmetic, as you mentioned: Altitude to Zenith

**Comment by MaxNoe** [comment]
Please do not do this! At least not without conferring first with CTA, pinging @kosack here.

We use altitude everywhere else. This is not a "cosmetic" change!

**Comment by labsaha** [comment]
@MaxNoe In the drive file the values are given Azimuth and Zenith. Hence to be consistent with that it is done in that way.

**Comment by MaxNoe** [comment]
Then you probably should convert into altitude on reading the input file before filling the container as everything after that, including astropy coordinates, expect altitude, not zenith.

**Comment by labsaha** [comment]
Well, that can be done. But It should not give the wrong message that in the drive report we have Altitude, because we are calling the `LSTDriveContainer`  where all field considered following the drive report.

**Comment by MaxNoe** [comment]
IMHO, consistency of the in-memory representations in ctapipe/lstchain would be preferable over consistency with the input files. 
This is also how these problems are usually handled best: at I/O boundaries conversions take place and internally everything should be consistent.

But this is just my 2 cents, maybe @kosack  or @bregeon can also comment.

I see that just the container is changed here. Is it just defined and not used in this repo?

**Comment by labsaha** [comment]
@MaxNoe I agree with that we should maintain the consistency. Initially, I thought of converting Zenith to Altitude before filling the container. However, at the same time, I thought about the field which is given in the drive logs. Finally, I have gone for the second one. I didn't realize that it might break the consistency in ctapipe. Anyway, I can close the PR once we hear from @kosack  @bregeon. And change associated changes in `lstchain`

**Comment by labsaha** [comment]
> I see that just the container is changed here. Is it just defined and not used in this repo?
If it is not used here, why is it here?

I cannot comment on this, even to my satisfaction. In the past, at one point it was decided somehow to put this here to include all monitoring information (one of them is drive log) in this container class.

**Comment by FrancaCassol** [comment]
Hi @MaxNoe,
 
> I see that just the container is changed here. Is it just defined and not used in this repo?
> If it is not used here, why is it here?

you are right, it could be filled here but somehow we didn't menage to converge toward this solution.

@labsaha I agree with @MaxNoe, please keep consistency with ctapipe.

**Comment by vuillaut** [comment]
> I see that just the container is changed here. Is it just defined and not used in this repo?
> If it is not used here, why is it here?

I think the idea was that this information should come with the data?

**Comment by labsaha** [comment]
Closing this PR and made required changes in `lstchain`

**Pull request closed without merging**
