### PR TITLE
Allow and test with ctapipe 0.19

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Review by rlopezcoto — APPROVED** [review]

**Comment by rlopezcoto** [comment]
shall we go for v0.21 so it can also be updated on cta-lstchain and use ctapipe v0.19? I don't think we need to go for v0.19.1 for us...

**Comment by maxnoe** [comment]
We should use it.

I would call this 0.20.1, since there are essentially no changes here.

**Comment by rlopezcoto** [comment]
a bump in ctapipe version should imply another one in ctapipe_io_lst, not a bugfix one, right?

**Comment by maxnoe** [comment]
Why? We did no changes to the code and we only *added* a supported version. 

We now support ctapipe 0.17 through 0.19

**Comment by rlopezcoto** [comment]
and bumped the required version of ctapipe as well.
Anyways, I am also ok with v0.20.1

**Comment by maxnoe** [comment]
> and bumped the required version of ctapipe as well.

No.

**Pull request merged**
